name: Java CI with Gradle

on:
  push:
    branches: [render]
  pull_request:
    branches: [render]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAIL: "b7531752@gmail.com"

    steps:
      - uses: actions/checkout@v3
      - name: imprimir variables
        run: |
          echo 'EL CORREO ES: '
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Path
        run: pwd

      - name: List
        run: ls -lasht src

      - name: Ejecutar Tests
        working-directory: src/test/java/evovital/uniquindio/edu/co
        run: ./gradlew test --tests evovital.uniquindio.edu.co.PacienteTest
