name: Java CI with Gradle

on:
  push:
    branches: [ render ]
  pull_request:
    branches: [ render ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MAIL: "b7531752@gmail.com"

    steps:
      - uses: actions/checkout@v3
      - name: imprimir variables
        run: |
          echo 'EL CORREO ES: '
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Path
        run: pwd

      - name: List
        run: ls -lasht src

      - name: Ejecutar Tests
        working-directory: ./
        run: ./gradlew test --tests evovital.uniquindio.edu.co.PacienteTest


  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: $ {{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API }}
